/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppGUI;

import ClassConstructor.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author cccccccccccccccccccc
 */
public class MainFrame extends javax.swing.JInternalFrame {

    QuanLySP qlsp;
    NhanVienGUI qlnv;
    QuanLyHDX qlhdx;
    QuanLyHDN qlhdn;
    BaoCaoBanHang bcbh;
    QuanLyNhomSP qlNhomSP;
    QuanLyKhuVuc qlKhuVuc;
    QuanLyKH qlKhachHang;
    QuanLyNCC qlNCC;

    NhanVien user;

    public static MainFrame it;

    public MainFrame(NhanVien user) {
        initComponents();

        this.user = new NhanVien();
        this.user = user;

        this.qlsp = new QuanLySP();
        this.qlnv = new NhanVienGUI();
        this.qlhdx = new QuanLyHDX(this.user);
        this.qlhdn = new QuanLyHDN(this.user);
        this.bcbh = new BaoCaoBanHang();
        this.qlNhomSP = new QuanLyNhomSP();
        this.qlKhuVuc = new QuanLyKhuVuc();
        this.qlKhachHang = new QuanLyKH();
        this.qlNCC = new QuanLyNCC();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qlspButton = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        qlnvButton = new javax.swing.JButton();
        qlHDXButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bcbhButoon = new javax.swing.JButton();
        qlNhomSpButton = new javax.swing.JButton();
        qlKhuVucButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        qlNCCButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý kho hàng");

        qlspButton.setText("Quản lý sản phẩm");
        qlspButton.setToolTipText("");
        qlspButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlspButtonActionPerformed(evt);
            }
        });

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1096, 731));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1097, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        qlnvButton.setText("Quản lý nhân viên");
        qlnvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlnvButtonActionPerformed(evt);
            }
        });

        qlHDXButton.setText("Quản lý hóa đơn xuất");
        qlHDXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlHDXButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("CHỌN CHỨC NĂNG");

        jLabel2.setText("MÀN HÌNH HIỂN THỊ CHỨC NĂNG");

        jButton1.setText("Quản lý hóa đơn nhập");
        jButton1.setPreferredSize(new java.awt.Dimension(153, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bcbhButoon.setText("Báo cáo thống kê");
        bcbhButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcbhButoonActionPerformed(evt);
            }
        });

        qlNhomSpButton.setText("Quản lý loại sản phẩm");
        qlNhomSpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlNhomSpButtonActionPerformed(evt);
            }
        });

        qlKhuVucButton.setText("Quản lý khu vực");
        qlKhuVucButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlKhuVucButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Quản lý khách hàng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        qlNCCButton.setText("Quản lý NCC");
        qlNCCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlNCCButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qlspButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlnvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlHDXButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bcbhButoon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlNhomSpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlKhuVucButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlNCCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qlnvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlspButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlHDXButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bcbhButoon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlNhomSpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlKhuVucButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(qlNCCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qlspButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlspButtonActionPerformed

        this.jDesktopPane1.add(qlsp);
        qlsp.setVisible(true);
    }//GEN-LAST:event_qlspButtonActionPerformed

    private void qlnvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlnvButtonActionPerformed

        this.jDesktopPane1.add(qlnv);
        qlnv.setVisible(true);
    }//GEN-LAST:event_qlnvButtonActionPerformed

    private void qlHDXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlHDXButtonActionPerformed
        this.jDesktopPane1.add(qlhdx);
        qlhdx.setVisible(true);
    }//GEN-LAST:event_qlHDXButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jDesktopPane1.add(qlhdn);
        qlhdn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bcbhButoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcbhButoonActionPerformed
        this.jDesktopPane1.add(bcbh);
        this.bcbh.setVisible(true);
    }//GEN-LAST:event_bcbhButoonActionPerformed

    private void qlNhomSpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlNhomSpButtonActionPerformed
        this.jDesktopPane1.add(qlNhomSP);
        this.qlNhomSP.setVisible(true);
    }//GEN-LAST:event_qlNhomSpButtonActionPerformed

    private void qlKhuVucButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlKhuVucButtonActionPerformed
        this.jDesktopPane1.add(qlKhuVuc);
        this.qlKhuVuc.setVisible(true);
    }//GEN-LAST:event_qlKhuVucButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jDesktopPane1.add(qlKhachHang);
        this.qlKhachHang.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void qlNCCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlNCCButtonActionPerformed
        this.jDesktopPane1.add(qlNCC);
        this.qlNCC.setVisible(true);
    }//GEN-LAST:event_qlNCCButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bcbhButoon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton qlHDXButton;
    private javax.swing.JButton qlKhuVucButton;
    private javax.swing.JButton qlNCCButton;
    private javax.swing.JButton qlNhomSpButton;
    public javax.swing.JButton qlnvButton;
    private javax.swing.JButton qlspButton;
    // End of variables declaration//GEN-END:variables
}
