/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppGUI;

import java.util.ArrayList;
import ClassConstructor.*;
import DAO.ClothesDAO;
import DAO.GroupClothesDAO;
import HandleData.IOfile;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cccccccccccccccccccc
 */
public class QuanLyNhomSP extends javax.swing.JInternalFrame {

    ArrayList<GroupClothes> listGroup;
    DefaultTableModel groupTableModel;
    int selectPosition = -1;

    /**
     * Creates new form QuanLyNhomSP
     */
    public QuanLyNhomSP() {
        initComponents();
        this.listGroup = new ArrayList<>();
        this.groupTableModel = (DefaultTableModel) this.tableGroupProduct.getModel();

//        this.listGroup = GroupClothesDAO;
        this.listGroup = GroupClothesDAO.getInstance().selectAll();

        this.showListGroup();
        this.tableGroupProduct.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectPosition = tableGroupProduct.getSelectedRow();
                idGroupText.setText((String) groupTableModel.getValueAt(selectPosition, 0).toString());
                nameGroupText.setText((String) groupTableModel.getValueAt(selectPosition, 1));
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    public void showListGroup() {
        this.groupTableModel.setRowCount(0);
        for (int i = 0; i < this.listGroup.size(); i++) {
            this.groupTableModel.addRow(new Object[]{
                this.listGroup.get(i).getID(),
                this.listGroup.get(i).getName(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableGroupProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idGroupText = new javax.swing.JTextField();
        nameGroupText = new javax.swing.JTextField();
        addGroup = new javax.swing.JButton();
        updateGroup = new javax.swing.JButton();
        deleteGroup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhóm sản phẩm");
        setPreferredSize(new java.awt.Dimension(1096, 731));

        tableGroupProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhóm", "Tên nhóm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableGroupProduct);
        if (tableGroupProduct.getColumnModel().getColumnCount() > 0) {
            tableGroupProduct.getColumnModel().getColumn(0).setResizable(false);
            tableGroupProduct.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("        Danh sách nhóm quần áo");

        jLabel2.setText("ID:");

        jLabel4.setText("Tên nhóm");

        addGroup.setText("Thêm nhóm");
        addGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupActionPerformed(evt);
            }
        });

        updateGroup.setText("Sửa nhóm");
        updateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGroupActionPerformed(evt);
            }
        });

        deleteGroup.setText("Xóa nhóm");
        deleteGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGroupActionPerformed(evt);
            }
        });

        jLabel5.setText("Tìm kiếm:");

        searchButton.setText("Tìm");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset DS");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idGroupText)
                            .addComponent(nameGroupText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(397, 397, 397)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idGroupText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGroup)
                    .addComponent(jLabel5)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(resetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateGroup)
                    .addComponent(jLabel4)
                    .addComponent(nameGroupText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteGroup)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupActionPerformed
        if (this.idGroupText.getText().length() == 0 || this.nameGroupText.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập đầy đủ thông tin vào ô trống");
        } else {
            GroupClothes newGR = new GroupClothes(Integer.parseInt(this.idGroupText.getText()), this.nameGroupText.getText());
            String checked = "";
            for (int i = 0; i <this.listGroup.size(); i++) {
                if (newGR.getID() == this.listGroup.get(i).getID()) {
                    checked = "fail";
                    break;
                }
            }
            if (checked.compareTo("fail") == 0) {
                JOptionPane.showMessageDialog(rootPane, "ID đã tồn tại !");
            } else {
                this.listGroup.add(newGR);
//                IOfile.writeGroupClothe(this.listGroup);
                GroupClothesDAO.getInstance().Add(newGR);
                this.idGroupText.setText("");
                this.nameGroupText.setText("");

                this.showListGroup();
                JOptionPane.showMessageDialog(rootPane, "Thêm nhóm thành công !");
            }
        }
    }//GEN-LAST:event_addGroupActionPerformed

    private void updateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGroupActionPerformed
        if (this.selectPosition == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn nhóm muốn cập nhật!");
        } else {
            int index = -1;
            for (int i = 0; i < this.listGroup.size(); i++) {
                if (Integer.parseInt(this.idGroupText.getText()) == this.listGroup.get(i).getID()) {
                    index = i;
                    break;
                }
            }
//            GroupClothes newGR = new GroupClothes(Integer.parseInt(this.idGroupText.getText()), this.nameGroupText.getText());
            this.listGroup.get(index).changePropeties(this.nameGroupText.getText());
//            IOfile.writeGroupClothe(this.listGroup);
            GroupClothesDAO.getInstance().Update(this.listGroup.get(index));
            this.idGroupText.setText("");
            this.nameGroupText.setText("");
            this.selectPosition = -1;

            this.showListGroup();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công !");
        }
    }//GEN-LAST:event_updateGroupActionPerformed

    private void deleteGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGroupActionPerformed
        if (this.selectPosition == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn nhóm muốn xóa!");
        } else {
            int index = -1;
            for (int i = 0; i < this.listGroup.size(); i++) {
                if (Integer.parseInt(this.idGroupText.getText()) == this.listGroup.get(i).getID()) {
                    index = i;
                    break;
                }
            }
            String checked = "";
            for (int i = 0; i < ClothesDAO.getInstance().selectAll().size(); i++) {
                if (this.listGroup.get(index).getID() == ClothesDAO.getInstance().selectAll().get(i).getIdNhom()) {
                    checked = "fail";
                    break;
                }
            }
            if (checked.compareTo("fail") == 0) {
                JOptionPane.showMessageDialog(rootPane, "Không thể xóa do có sản phẩm thuộc nhóm này");
            } else {
//                GroupClothes newGR = new GroupClothes(Integer.parseInt(this.idGroupText.getText()), this.nameGroupText.getText());
//                this.listGroup.remove(index);
//                IOfile.writeGroupClothe(this.listGroup);
                GroupClothesDAO.getInstance().Delete(this.listGroup.get(index));
                this.listGroup.remove(index);
                this.idGroupText.setText("");
                this.nameGroupText.setText("");
                this.selectPosition = -1;

                this.showListGroup();
                JOptionPane.showMessageDialog(rootPane, "Xóa nhóm thành công !");
            }
        }
    }//GEN-LAST:event_deleteGroupActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.showListGroup();
        this.searchText.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (this.searchText.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Nhập tên nhóm muốn tìm kiếm!");
        } else {
            ArrayList<GroupClothes> listGroupClone = new ArrayList<>();
            for (int i = 0; i < this.listGroup.size(); i++) {
                if (this.listGroup.get(i).getName().indexOf(this.searchText.getText()) != -1) {
                    listGroupClone.add(this.listGroup.get(i));
                }
            }
            this.groupTableModel.setRowCount(0);
            for (int i = 0; i < listGroupClone.size(); i++) {
                this.groupTableModel.addRow(new Object[]{
                    listGroupClone.get(i).getID(),
                    listGroupClone.get(i).getName(),});
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup;
    private javax.swing.JButton deleteGroup;
    private javax.swing.JTextField idGroupText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameGroupText;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    private javax.swing.JTable tableGroupProduct;
    private javax.swing.JButton updateGroup;
    // End of variables declaration//GEN-END:variables
}
